### ISSUE TITLE
Something's wrong with #define

### ISSUE THREAD

**Issue by macks2008** [object-Object/vscode-hex-casting#19] opened 2024-07-12 20:50 UTC
I'm not sure how to describe this so a screenshot will have to do:
![image](https://github.com/user-attachments/assets/78811383-46ee-40f3-8a57-bfc1176e1660)
See what's wrong with the syntax highlighting? The angle signature ends at the first parenthesis, and the macro can be referenced as normal, but the highlighting treats it as if the whole thing is part of the angle signature. Is there some RegEx shenanigans going on here?

**Comment by object-Object** [comment] 2024-07-12 20:51
yeah, duplicate of #18. i'll try and remember to get around to fixing it, sorry

**Comment by macks2008** [comment] 2024-07-12 20:52
Just to demonstrate that the define directive is still able to isolate the angle signature properly. This seems to be JUST the code style
![image](https://github.com/user-attachments/assets/964bf61e-ed5d-4b3b-a6ef-140ef14c8d36)

**Comment by macks2008** [comment] 2024-07-12 20:52
And okay

**Closed by object-Object** 2024-07-12 20:51 UTC
