### ISSUE TITLE
macro definitions error if not indented

### ISSUE THREAD

**Issue by macks2008** [object-Object/vscode-hex-casting#8] opened 2023-07-05 00:02 UTC
the error says "malformed #define directive", but apparently they just need a bit of white space indenting before the hashmark, for some reason.
this errors:
![image](https://github.com/object-Object/vscode-hex-casting/assets/7110033/63349003-831e-4f2c-bf46-2d69a6d1d1da)
![image](https://github.com/object-Object/vscode-hex-casting/assets/7110033/7c7d3d5c-6caa-44e3-bb6d-d7dd5cddf328)
this doesn't error:
![image](https://github.com/object-Object/vscode-hex-casting/assets/7110033/9c1e8cb1-38e9-4f46-bc8d-4ce8c4c1596d)
![image](https://github.com/object-Object/vscode-hex-casting/assets/7110033/e2de9037-6c91-4352-99cb-bb9a6c3adfee)

**Comment by macks2008** [comment] 2023-07-05 00:15
(the issue is not the empty pattern signature, I just didn't screenshot an example of that)

**Comment by object-Object** [comment] 2023-07-05 00:22
The issue is actually the empty signature. The latter image isn't erroring because it's not recognized as a #define at all due to the (illegal) leading whitespace.

**Comment by macks2008** [comment] 2023-07-05 01:55
Oh, I stand corrected, I could've sworn this didn't work at one point. Though now I'm getting a different error, saying invalid direction. 
![image](https://github.com/object-Object/vscode-hex-casting/assets/7110033/14587774-f5b7-44bc-abeb-f526ccce37f4)
..Though looking at the code you have in hex-hexes, I realized this is another mistake on my part.. The error means STARTING DIRECTION. For some reason I only tend to treat the angles as the signature since the starting direction is normally only used when rendering a scroll/slate or for Painter's.

conclusion: user error
Suggested resolution: make error messages more descriptive. The first one just says "malformed define directive" which is rather vague, and the latter could probably say "invalid starting direction" just to be clear.

**Comment by object-Object** [comment] 2023-08-13 21:34
Fixed in `0.1.23`.

**Closed by object-Object** 2023-08-13 21:34 UTC
